version: "3"
services:
  neo4j:
    image: neo4j:4.1
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
    - dbdata:/data

  api:
    build:
      context: ./
    ports:
    - "8080:8080"
    depends_on:
      - neo4j

volumes:
  dbdata: {}